export const POLISH_CITIES = [
  "Augustów", "Bełchatów", "Będzin", "Biała Podlaska", "Białystok", "Bielawa", "Bielsko-Biała", 
  "Bolesławiec", "Brodnica", "Bydgoszcz", "Bytom", "Chełm", "Chojnice", "Chorzów", "Ciechanów", 
  "Cieszyn", "Czeladź", "Czechowice-Dziedzice", "Częstochowa", "Dąbrowa Górnicza", "Dębica", 
  "Dzierżoniów", "Elbląg", "Ełk", "Gdańsk", "Gdynia", "Giżycko", "Gliwice", "Głogów", "Gniezno", 
  "Gorzów Wielkopolski", "Grodzisk Mazowiecki", "Grudziądz", "Iława", "Inowrocław", "Jarosław", 
  "Jasło", "Jastrzębie-Zdrój", "Jaworzno", "Jelenia Góra", "Kalisz", "Katowice", "Kielce", 
  "Kluczbork", "Kłodzko", "Knurów", "Kołobrzeg", "Konin", "Koszalin", "Kraków", "Kraśnik", 
  "Krosno", "Kutno", "Kwidzyn", "Legionowo", "Legnica", "Leszno", "Lębork", "Lubin", "Lublin", 
  "Luboń", "Łomża", "Łódź", "Łuków", "Malbork", "Marki", "Mielec", "Mikołów", "Mińsk Mazowiecki", 
  "Mysłowice", "Nowa Sól", "Nowy Sącz", "Nowy Targ", "Nysa", "Olsztyn", "Oława", "Opole", 
  "Ostrołęka", "Ostrowiec Świętokrzyski", "Ostrów Wielkopolski", "Oświęcim", "Otwock", 
  "Pabianice", "Piaseczno", "Piekary Śląskie", "Piła", "Piotrków Trybunalski", "Płock", "Police", 
  "Poznań", "Pruszków", "Przemyśl", "Puławy", "Racibórz", "Radom", "Radomsko", "Reda", 
  "Ruda Śląska", "Rumia", "Rybnik", "Rzeszów", "Sanok", "Siedlce", "Siemianowice Śląskie", 
  "Sieradz", "Skarżysko-Kamienna", "Skierniewice", "Słupsk", "Sopot", "Sosnowiec", "Stalowa Wola", 
  "Starachowice", "Stargard", "Starogard Gdański", "Suwałki", "Szczecin", "Szczecinek", "Świdnica", 
  "Świebodzice", "Świętochłowice", "Świnoujście", "Tarnobrzeg", "Tarnów", "Tczew", 
  "Tomaszów Mazowiecki", "Toruń", "Tychy", "Wałbrzych", "Warszawa", "Wejherowo", "Włocławek", 
  "Wodzisław Śląski", "Wołomin", "Wrocław", "Września", "Zabrze", "Zakopane", "Zamość", 
  "Zawiercie", "Ząbki", "Zduńska Wola", "Zgierz", "Zgorzelec", "Zielona Góra", "Żagań", 
  "Żory", "Żywiec", "Żyrardów"
];